### ISSUE TITLE
 TypeError: Cannot read property 'changes' of undefined

### ISSUE THREAD

**Issue by guyappy** [A21z/node-cd#14]
Hi,

I get the following error, would be great if you can give me some pointers to look at to solve this problem.

Thanks a million!

```
Node-cd server listening on port 61440
{"readable":false,"_maxListeners":10,"httpVersion":"1.1","complete":true,"_pendingIndex":0,"url":"/bitbucket","method":"POST","_consuming":true,"_dumped":false,"httpVersionMajor":1,"httpVersionMinor":1,"upgrade":false,"baseUrl":"","originalUrl":"/bitbucket","_remoteAddress":"104.192.143.193","_body":true}
104.192.143.193 - - [07/Mar/2016:19:02:13 +0000] "POST /bitbucket HTTP/1.1" 500 1385 "-" "Bitbucket.org"
TypeError: Cannot read property 'changes' of undefined
    at Bitbucket.post (/home/x/swaggerUI-h10/node-cd-2.0.0/src/routes/bitbucket.js:17:30)
    at Layer.handle [as handle_request] (/home/x/swaggerUI-h10/node-cd-2.0.0/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/x/swaggerUI-h10/node-cd-2.0.0/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/x/swaggerUI-h10/node-cd-2.0.0/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/x/swaggerUI-h10/node-cd-2.0.0/node_modules/express/lib/router/layer.js:95:5)
    at /home/x/swaggerUI-h10/node-cd-2.0.0/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/x/swaggerUI-h10/node-cd-2.0.0/node_modules/express/lib/router/index.js:330:12)
    at next (/home/x/swaggerUI-h10/node-cd-2.0.0/node_modules/express/lib/router/index.js:271:10)
    at serveStatic (/home/x/swaggerUI-h10/node-cd-2.0.0/node_modules/express/node_modules/serve-static/index.js:74:16)
    at Layer.handle [as handle_request] (/home/x/swaggerUI-h10/node-cd-2.0.0/node_modules/express/lib/router/layer.js:95:5)
```

Thanks for the module by the way, I checked the code and I really like it!!

**Comment by A21z** [comment]
Hello @guyappy, thank you for reporting this!

Is this error happening after a push or some other operation (fork, commit status changed, issue or PR action)?

node-cd currently only supports push webhooks. If you don't need other webhooks you could unckeck them as a workaround:
![possible webhooks](https://confluence.atlassian.com/bitbucket/files/304578655/add_webhook.png)

If you need to handle another webhook you're welcome to contribute. I can help you with that if you need.

Anyways I'm keeping this issue open until I have at least a graceful way to ignore non-push webhooks.

**Comment by guyappy** [comment]
thanks for the response! This weekend I'll try it out with a webhook. Also I'll test the 204 :+1:
